include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    library_private_types_in_public_api: ignore

  exclude:
    - lib/assets/gen**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"